### PR TITLE
 [ci skip] [skip ci] [cf admin skip] ***NO_CI*** Add core Globus Compute developers as maintainers

### PR DESCRIPTION
**Pull request by rjmello**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carterbox** [comment]
@conda-forge-admin, please rerender

**Comment by carterbox** [comment]
I guess I should be able to see you in the @conda-forge/globus-compute-sdk team list, and I should be kicked off the team.

**Comment by carterbox** [comment]
I made a mistake in adding ci skip to the commit message. I thought that ci skip was only for building the package, but apparently it is also for the bot which manages the access teams.

**Comment by rjmello** [comment]
> @rjmello, do you have access to this repository now? I'm not sure how long it takes for the bot to notice changes.

Looks all good to me; thanks!

**Pull request merged**
